### ISSUE TITLE
Generate federated schema

### ISSUE THREAD

**Issue by AlexKlim** [Gusto/apollo-federation-ruby#106]
Hi all, 
I want to generate a federated schema. But I get the schema without any directives/etc.

for instance, I have

```ruby
class UsersSchema < GraphQL::Schema
  include ApolloFederation::Schema

  orphan_types Types::UserType
end

module Types
  class UserType < Types::BaseObject
    extend_type
    key fields: 'id'
    field :id, ID, null: false, external: true
  end
end
```

when I use a [general way](https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/rake_task.rb) to generate schema into SDL, JSON, I get an incorrect federated schema

```GraphQL
type User {
  id: ID!
}

type Query {
  _entities(representations: [_Any!]!): [_Entity]!
  _service: _Service!
}

scalar _Any

union _Entity = User

"""
The sdl representing the federated service capabilities. Includes federation
directives, removes federation types, and includes rest of full schema after
schema directives have been applied
"""
type _Service {
  sdl: String
}
```

How can I generate a federated schema?

**Comment by brettfishman** [comment]
Hello 👋  

I think you're looking for something like this? 

```
# Returns the sdl (schema definition language) representing the federated service capabilities. Includes federation
# directives, removes federation types, and includes rest of full schema after schema directives have been applied.
sdl_query = <<-GQL
    {
      _service {
        sdl
      }
    }
GQL

UsersSchema.execute(sdl_query)
```

I ran into this same issue myself, and someone on the Apollo team provided this solution. Let me know if that works for you.

**Comment by lennyburdette** [comment]
`puts UsersSchema.federation_sdl` is even better! I just opened a PR to add this to the readme: https://github.com/Gusto/apollo-federation-ruby/pull/126
