### ISSUE TITLE
[question] Is this project maintained?

### ISSUE THREAD

**Issue by linhdangduy** [Gusto/apollo-federation-ruby#115]
Firstly, thank so much for the gem!

We consider to use this gem, but the last update is 2020/10 and seem there are no activities since that time. Is there a plan to continue maintain this gem?

**Comment by BatuhanW** [comment]
We are using this gem production for a while and it does the job.

**Comment by rtymchyk** [comment]
The gem may have a lack of updates because the the federation spec is pretty simple, so there's not a whole lot to maintain. Regardless, we've been using the core functionality in production for a while without problems as well. Tracing is a little iffy but it's optional.

**Comment by linhdangduy** [comment]
I also see that [the federation spec is not updated since 2020/10](https://github.com/apollographql/federation/blob/main/docs/source/api/apollo-federation.mdx), so agree there are no big update here.

Things I just worry is there are [pull requests](https://github.com/Gusto/apollo-federation-ruby/pulls) are not resolved. It is so helpful if the maintainers spend time discuss , or close stale one, or just merge the dependent bot pulls if it not bring break changes.

anw, we are in progress to use this gem in our project, too.

Thank you very much.
