### ISSUE TITLE
Readme Beta Comment

### ISSUE THREAD

**Issue by Austio** [Gusto/apollo-federation-ruby#118]
:wave: Hello, thank you for this fantastic contribution to graphql ruby. 

Is this system actually in "beta" mode as the README state?  I have used this in a relatively complex scenario and it seems to be fully spec compliant.  

If that is the case, would you accept a PR to remove the beta declaration out of the README?

Thanks again!

**Comment by daemonsy** [comment]
Likewise, we are actively using this library in our main user facing applications. 

As a consumer of open source library, I would prefer libraries to list out limitations than having a beta disclaimer. 

Happy to take a PR to remove the disclaimer.
