### ISSUE TITLE
Support for schema registration

### ISSUE THREAD

**Issue by gtkatakura** [Gusto/apollo-federation-ruby#123]
Hey, guys. How you are dealing with publishing your services schemas to the gateway? Are you using something similar to [schema registration](https://www.apollographql.com/docs/studio/schema/schema-reporting/)?

**Comment by rtymchyk** [comment]
I am using the Apollo CLI to publish a printed out schema to the managed service. As long as the gateway connects to Apollo Studio, it will pick up any changes. 

https://www.apollographql.com/docs/studio/schema/cli-registration/
