### ISSUE TITLE
Support for federated tracing

### ISSUE THREAD

**Issue by lennyburdette** [Gusto/apollo-federation-ruby#14]
Tracing works differently in a federated system than it does for a standard GraphQL server. It's officially [documented here](https://www.apollographql.com/docs/apollo-server/federation/metrics/).

Question 1: do you think this library should include support for generating the trace proto and attaching it to the response? It could be a separately library, but I think it makes sense to include all federation concerns in one place.

Question 2: is anyone working on this?

The node.js implementation is here:

* [report.proto](https://github.com/apollographql/apollo-server/blob/master/packages/apollo-engine-reporting-protobuf/src/reports.proto)
* [treeBuilder.ts](https://github.com/apollographql/apollo-server/blob/master/packages/apollo-engine-reporting/src/treeBuilder.ts)
* [federatedExtension.ts](https://github.com/apollographql/apollo-server/blob/master/packages/apollo-engine-reporting/src/treeBuilder.ts)

There's some unfinished ruby work for standard single-server traces (that are sent directly to Apollo's traces ingress endpoint instead of attached to the response to the gateway) [here](https://github.com/salsify/apollo-tracing-ruby/tree/feature/new-apollo-api).

**Comment by rylanc** [comment]
Hi @lennyburdette!

1. I haven't given much thought to tracing yet (our gateway isn't live in production quite yet). From my understanding of federated tracing, it seems pretty specific to federation. So, it would make sense for the Ruby implementation to live in this repo.

2. To my knowledge, no one has attempted to implement this in Ruby. Are you feeling up to the task? 🙂 I'm happy to chip in, but I don't know how much time I can dedicate to it for the next few weeks.

**Comment by lennyburdette** [comment]
👋 Rylan! 

Definitely agree that federated tracing is _just_ different enough from standard tracing that it belongs here.

I'll have several hours on a plane with a laptop over the weekend so I'll get something started!
