### ISSUE TITLE
Compatibility with Mac M1's

### ISSUE THREAD

**Issue by LiChoi** [Gusto/apollo-federation-ruby#144]
When trying to do rails:db migrate, I encounter this error message due to apollo-federation gem:

rails aborted!
LoadError: cannot load such file -- google/protobuf_c

google/protobuf is the issue, but not sure how to solve this
https://github.com/protocolbuffers/protobuf/issues/8062

**Comment by bjacobso** [comment]
We are seeing a similar issue: 
```
./bin/rails db:create db:migrate db:seed   
rails aborted!
LoadError: cannot load such file -- google/protobuf/descriptor_pb
```

**Comment by daemonsy** [comment]
Hopefully https://github.com/Gusto/apollo-federation-ruby/pull/150 and optionally, a version bump of `google-protobuf` will resolve M1 related issues. 

I don't have a machine to reproduce the issue, but if folks who bumped into it can post bundler environment info, I'd appreciate it.
