### ISSUE TITLE
uninitialized constant GraphQL::Define

### ISSUE THREAD

**Issue by modosc** [Gusto/apollo-federation-ruby#175]
we recently upgraded from `1.1.5` to `2.2.0` and started getting `uninitialized constant GraphQL::Define` errors in our specs.

https://github.com/Gusto/apollo-federation-ruby/blob/1d3baf4f8efcd02e7bf5bc7e3fee5b4fb963cd25/lib/apollo-federation/federated_document_from_schema_definition.rb#L59

as far as i can tell that class no longer exists in the graphql gem:

https://github.com/rmosolgo/graphql-ruby/search?q=InstanceDefinable

**Comment by daemonsy** [comment]
We don't support GraphQL 2.0 officially yet, but in #176, the author has added 2.0 to the matrix. 

I can only look into this next week but if you like to tackle it, happy to take a PR!

**Comment by modosc** [comment]
thanks - this fixes it for us.
