### ISSUE TITLE
Enabling federated tracing breaks multiplex

### ISSUE THREAD

**Issue by ivanbrennan** [Gusto/apollo-federation-ruby#197]
In a Rails app with a controller that supports [query-batching via multiplex](https://graphql-ruby.org/queries/multiplex.html#apollo-query-batching), enabling federated tracing ([using the documented steps](https://github.com/Gusto/apollo-federation-ruby#tracing)) leads to a runtime error when processing batched queries.

#### Repro

Controller action:
```ruby
  def execute
    context = {
      tracing_enabled: ApolloFederation::Tracing.should_add_traces(request.headers),
    }

    multi = params[:_json]
    result =
      if multi
        MySchema.multiplex(
          multi.map do |param|
            {
              query: param[:query],
              operation_name: param[:operationName],
              variables: prepare_variables(param[:variables]),
              context: context
            }
          end
        )
      else
        MySchema.execute(
          params[:query],
          operation_name: params[:operationName],
          variables: prepare_variables(params[:variables]),
          context: context
        )
      end

    render json: result
  end
```

The following requests succeed:
```sh
# single query
$ curl localhost:3000/graphql -H 'content-type: application/json' -d '{"query":"query{__schema{__typename}}"}'
{"data":{"__schema":{"__typename":"__Schema"}}}

# batch of 1
$ curl localhost:3000/graphql -H 'content-type: application/json' -d '[{"query":"query{__schema{__typename}}"}]'
[{"data":{"__schema":{"__typename":"__Schema"}}}]
```

The following request fails:
```sh
# batch of 2
$ curl localhost:3000/graphql -H 'content-type: application/json' -d '[{"query":"query{__schema{__typename}}"},{"query":"query{__schema{__typename}}"}]'
```
```
Completed 500 Internal Server Error in 1831ms (Allocations: 7241)

NoMethodError (undefined method `context' for nil:NilClass):

apollo-federation (3.0.0) lib/apollo-federation/tracing/tracer.rb:87:in `execute_query_lazy'
apollo-federation (3.0.0) lib/apollo-federation/tracing/tracer.rb:48:in `trace'
graphql (2.0.5) lib/graphql/tracing.rb:82:in `call_tracers'
graphql (2.0.5) lib/graphql/tracing.rb:66:in `trace'
graphql (2.0.5) lib/graphql/execution/interpreter.rb:71:in `sync_lazies'
graphql (2.0.5) lib/graphql/execution/interpreter.rb:32:in `finish_multiplex'
graphql (2.0.5) lib/graphql/execution/multiplex.rb:88:in `block (3 levels) in run_all'
graphql (2.0.5) lib/graphql/dataloader.rb:181:in `block in run'
graphql (2.0.5) lib/graphql/dataloader.rb:303:in `block in spawn_fiber'
```

#### Relevant code

I don't know the inner workings well enough to connect all the dots, but here a few relevant pieces of code I plucked from the backtrace.

https://github.com/Gusto/apollo-federation-ruby/blob/4a78028a13c41f0cf653eea6caa2585e3549c8f1/lib/apollo-federation/tracing/tracer.rb#L85-L86
Note that in the error case, `data[:query]` is `nil` (whereas `data[:multiplex]` is present).

https://github.com/rmosolgo/graphql-ruby/blob/42337a85aacf7f2010500e11f57fd6b8d58e1cb1/lib/graphql/execution/interpreter.rb#L61-L62
```ruby
  if query.nil? && multiplex.queries.length == 1
    query = multiplex.queries[0]
  end
```
This seems to explain why the error is not thrown for a batch of 1.

**Comment by jesstice** [comment]
We are currently running into this issue as well. Did you ever find a workaround @ivanbrennan?

**Comment by ivanbrennan** [comment]
> We are currently running into this issue as well. Did you ever find a workaround @ivanbrennan?

@jesstice Unfortunately no. I had to drop support for multiplex.

**Comment by grxy** [comment]
@jesstice @ivanbrennan If you are able, please try upgrading to the latest version and let me know if things are working for you. Thanks to @ashleyyy for implementing a fix!

**Comment by ashleyyy** [comment]
Thanks @grxy for the speedy review and release! This solved my issue before I could even deploy my workaround 😁
