### ISSUE TITLE
unable to configure federation directive namespace

### ISSUE THREAD

**Issue by thumbnail** [Gusto/apollo-federation-ruby#201]
In federation version 2 the directives have namespaces (`federation__` by default). Currently this prefix is non-configurable which may cause issues when other subgraphs use a different namespace or import them without a namespace. 

In Apollo studio I got the following error:

```
The federation "@inaccessible" directive is imported with mismatched name between subgraphs: it is imported as "@inaccessible" in subgraphs "X" and "Y" but "@federation__inaccessible" in subgraphs "A" and "B"
```

In this case, A and B are ruby applications, and X and Y are not. 

It can be partially fixed by configuring the graph as v1 and overriding `Schema#federation_dsl` to prepend an import for all directives. But it's not very elegant 😬

**Comment by geshwho** [comment]
Hey @thumbnail, thanks for reporting this! @daemonsy and I will take a look this week.

**Comment by geshwho** [comment]
Hey @thumbnail, we took a look at this today and it seems like there are a couple of enhancements that would help us get closer to spec compliant with federation version 2.
- We need to provide an option that allows the user to override the default namespace (similar to the example in the [docs](https://www.apollographql.com/docs/federation/federation-spec/#link) which uses `fed2` as the namespace)
- We need to provide an option for users to specify the `import` argument on the link directive such that they will not be prefixed. From the docs:
> The import argument enables you to import external definitions into your namespace, so they are not prefixed.

I believe the latter one would help resolve the issue that you are seeing. Do you have any interest in working on a solution for either of these enhancements?

**Comment by geshwho** [comment]
Hey @lennyburdette, I was just rereading your comment [here](https://github.com/Gusto/apollo-federation-ruby/pull/196#issuecomment-1139067046) and realized that it directly conflicts with what I just suggested [above](https://github.com/Gusto/apollo-federation-ruby/issues/201#issuecomment-1176546053). Namely, per your comment, code-first libraries will not be providing an API to rename imports (second bullet point). However, I wanted to ask: should we consider an API to allow overriding the default namespace (first bullet point)?

**Comment by lennyburdette** [comment]
Hmm this is odd. It appears to me that this error occurs with `@inaccessible` but not `@key` or `@shareable` so I think this is a bug related to backward-compatibility with `@tag` and `@inaccessible`. I'll reach out to the team tomorrow and get back to you.

https://github.com/apollographql/federation/blob/main/composition-js/src/merging/merge.ts#L198-L201
https://github.com/apollographql/federation/blob/main/composition-js/src/merging/merge.ts#L285-L287
https://github.com/apollographql/federation/blob/main/composition-js/src/merging/merge.ts#L292-L322

**Comment by lennyburdette** [comment]
I had a good conversation with my team about this and learned a bunch. I still consider this a bug, but it may not be a high priority to fix. And we'll eventually need an API for configuring future `@link`ed directives, so it's probably worth addressing now.

Here's my summary of the conversation: https://github.com/apollographql/federation/issues/1976#issuecomment-1182131463

**Comment by grxy** [comment]
I'm going to close this since this was solved in https://github.com/Gusto/apollo-federation-ruby/commit/03fdfeafaaea3c98ca4b7a734ce760ea08410530
