### ISSUE TITLE
Improve reference resolving performance

### ISSUE THREAD

**Issue by tjwallace** [Gusto/apollo-federation-ruby#21]
Currently only one reference can be loaded at a time, and because the type is attached to the context, lazy objects can't be used.

Some ideas:
1. Figure out how to use lazy objects, or a different way of resolving types in `ApolloFederation::Entity.resolve_type`.
2. Allow each GraphQL type to define a `.resolve_references(references, context)` method that can load multiple references at the same time.

I think idea 2 would be pretty straight forward to implement and a quick stopgap until idea 1 can be implemented.

Any thoughts?

**Comment by cmschuetz** [comment]
This should provide a solution to suggestion 1: https://github.com/Gusto/apollo-federation-ruby/pull/17

**Comment by rylanc** [comment]
@tjwallace Now that https://github.com/Gusto/apollo-federation-ruby/pull/17 has landed, is that enough to allow loading multiple references at once? Can you give me an example of when you would want to do that?

**Comment by tjwallace** [comment]
@rylanc I'm going to go now that lazy objects are supported, thanks!
