### ISSUE TITLE
Add `resolvable` argument to `key` directive

### ISSUE THREAD

**Issue by BPMathews** [Gusto/apollo-federation-ruby#217]
Apollo documentation describes how to [reference an entity without contributing fields](https://www.apollographql.com/docs/federation/entities/#referencing-an-entity-without-contributing-fields). The `resolvable` argument on the `key` field indicates to Apollo that the subgraph is only referencing the entity and has no resolver. 

I looked at the key implementation [here](https://github.com/Gusto/apollo-federation-ruby/blob/fc541eec17768db614efc62d3d0217eace9bf354/lib/apollo-federation/object.rb#L27) and didn't see a way set this argument in my subgraph. 

Could this be added in order to fulfill this aspect of federation? 

**Schema Example**
```
type Product @key(fields: "id", resolvable: false) {
  id: ID!
}
```

**Comment by grxy** [comment]
@BPMathews Thanks for pointing this out! Feel free to open a PR if you're up to it! CC: @sethc2
