### ISSUE TITLE
Support for .define-style schemas

### ISSUE THREAD

**Issue by jstrater** [Gusto/apollo-federation-ruby#23]
From the known issues and limitations section in the README:

> - Currently only works with class-based schemas

It makes perfect sense that you'd implement this for class-based schemas first, since that seems to be the future of `graphql-ruby`. Are there any plans to support the `.define`-style schemas as well?

I have a large `.define`-style schema and I'd love to be able to use this gem with it!

**Comment by rtymchyk** [comment]
Does the full schema need to be converted to class-based style?

**Comment by rylanc** [comment]
Closing this, since we (unfortunately) will probably never support `.define` schemas. They're quickly being deprecated in graphql-ruby as well.
