### ISSUE TITLE
Question around code in docs.

### ISSUE THREAD

**Issue by ryannealmes** [Gusto/apollo-federation-ruby#25]
In the [docs](https://github.com/Gusto/apollo-federation-ruby#getting-started) you have the following

```ruby
class BaseObject < GraphQL::Schema::Object
  include ApolloFederation::Object

  field_class BaseField # what is this for?
end
```
What is the purpose of the second last line?

**Comment by noaelad** [comment]
Thanks for the question!
The `field_class` method is a way of specifying the class that fields are created with when they are defined in your schema. This is essentially following this guide:
https://graphql-ruby.org/type_definitions/extensions#customizing-fields

Hope that helps!

**Comment by rylanc** [comment]
Closing this. Feel free to reopen if there are more questions
