### ISSUE TITLE
Namespace all federation directives

### ISSUE THREAD

**Issue by jturkel** [Gusto/apollo-federation-ruby#251]
There's probably some history here but it would be nice to have consistent namespacing of federation directives. Currently `@inaccessible` and `@tag` are not namespaced but all other federation directives are namespaced e.g. `@key` is exposed as `@federation__key`. apollo-federation-ruby could make the set of imported directives configurable but I'm not sure there's sufficient value in doing that vs. just namespacing everything to avoid conflicts with other directives. I'd be happy to put up a PR if you're open to this change.

**Comment by grxy** [comment]
[This comment](https://github.com/apollographql/federation/issues/1976#issuecomment-1184522540) talks about why `@inaccessible` and `@tag` are imported vs namespaced.

**Comment by jturkel** [comment]
Ah! Makes sense.
