### ISSUE TITLE
Consider snake_case for fields

### ISSUE THREAD

**Issue by cmschuetz** [Gusto/apollo-federation-ruby#36]
While implementing the federation spec for a few types, I got tripped up when referencing fields in the `key` helper and `resolve_reference`.  Since all of the fields in `graphql-ruby` use snake case, I sometimes forget that the helpers for federation use the actual camelCased field names.

When authoring this library, was snake_case considered, and if so were there any reasons to not use it?  I feel as though the mix of snake & camel case may be slightly confusing, what are your thoughts?

**Comment by prikha** [comment]
I second that 👍 

I like `graphql-ruby`'s handy convention.

https://graphql-ruby.org/type_definitions/objects.html#object-classes

Since federation serves as an extension it would be nice to naturally follow the same conventions...
