### ISSUE TITLE
Support for graphql 1.10+

### ISSUE THREAD

**Issue by fgrehm** [Gusto/apollo-federation-ruby#48]
Hey there!

I've just started playing with this gem, so far so good, tks for getting this released :beer:  While I was experimenting with things, I tried to update to the recently released [graphql 1.10.0](https://github.com/rmosolgo/graphql-ruby/blob/master/CHANGELOG.md#1100-20-jan-2020) but found out that this gem is not compatible with it.

Was there a specific reason for locking the dep to 1.9.x? I haven't gone through the sources of this project yet and there are some breaking changes on 1.10.0 (and it is also supposed to yield [faster boot times](https://github.com/rmosolgo/graphql-ruby/pull/2363#issuecomment-562191562), which is why we were considering upgrading it :zap: )

**Comment by HectorMF** [comment]
Hi @fgrehm I was needing some of the connection features that were added to graphql 1.10.0 so I had a go at updating. There are some breaking changes.  I've made a pull request with the necessary changes: #49

**Comment by rylanc** [comment]
The latest release (1.1.0) should fix compatibility issues with graphql 1.10.0. Please refile an issue if you run into any more trouble.
