### ISSUE TITLE
Passing data in context will cause a crash

### ISSUE THREAD

**Issue by rjordan** [Gusto/apollo-federation-ruby#53]
Given a schema call with context    
result = schema.execute(
      query,
      operation_name: operation_name,
      variables: vars,
      context: { current_user: 'Bob' }
    )

{:query=>"query GetServiceDefinition { _service { sdl } }", :operationName=>nil, :vars=>{}, :schema=>ProductSchema}

will result in

ERROR ArgumentError: unknown keyword: current_user

Given a token we include the current user in all contexts.  I would not expect this to be an issue however.

**Comment by rtymchyk** [comment]
Looks like duplicate ohttps://github.com/Gusto/apollo-federation-ruby/issues/51

**Comment by rylanc** [comment]
Closing as this looks to be fixed in https://github.com/Gusto/apollo-federation-ruby/pull/45
