### ISSUE TITLE
Cannot use new interpreter with apollo-federation-ruby

### ISSUE THREAD

**Issue by tjwallace** [Gusto/apollo-federation-ruby#63]
Using the [new `graphql-ruby` interpreter](https://graphql-ruby.org/queries/interpreter.html) with `apollo-federation-ruby` does not work.

* Query: `{ _service { sdl } }`
* Error: `Field '_service' doesn't exist on type 'Query'`

### Schema
```ruby
class AppSchema < GraphQL::Schema
  include ApolloFederation::Schema

  use GraphQL::Execution::Interpreter
  use GraphQL::Analysis::AST

  # ...
end
```

### Versions
* `graphql-ruby`: `1.10.7`
* `apollo-federation-ruby`: `1.0.4`

**Note:** The new interpreter + `apollo-federation-ruby` did work with `graphql-ruby` `1.9.19`.

**Comment by bilby91** [comment]
Having the same issue with GraphQL 1.10

**Comment by bilby91** [comment]
I've been doing some experimentation with adding support for the new interpreter. I have it working but the changes will probably require to change the approach on how the federation is setup.

I can probably send a MR to discuss this. I also found that the current implementation of overriding the root query breaks other dependencies like `graphql-guard`.

**Comment by bilby91** [comment]
I'm trying to see if we can use/build an API that would let us hook the different pieces that are needed for federation here https://github.com/rmosolgo/graphql-ruby/issues/2928
