### ISSUE TITLE
Creating service and gateway in Rails

### ISSUE THREAD

**Issue by coduccin** [Gusto/apollo-federation-ruby#96]
Has anyone had any success building and running federated services and a gateway in a Rails app? I already have federated my schema and am trying to get each GraphQLServer running for each service.

**Comment by rtymchyk** [comment]
Your best bet is federated Rails app, and using a Node apollo-gateway for merging the services together.

**Comment by daemonsy** [comment]
Thanks for responding to this, @rtymchyk and that's the approach we currently use to tie services together.
